apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    type: db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: account-mongodb
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        type: db
        service: account-mongodb
    spec:
      containers:
      - env:
        - name: INIT_DUMP
          value: account-service-dump.js
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mongodb-password
{{- if or (eq .Values.environment "uat") (eq .Values.environment "prod") }}
        image: zanhsieh/{{ .Chart.Name }}-mongodb:release - {{- .Values.environment -}} - {{- $.Values.region -}} -latest
{{- else }}
        image: zanhsieh/{{ .Chart.Name }}-mongodb:{{- .Values.environment -}} - {{- $.Values.region -}} -latest
{{- end }}
        name: account-mongodb
        ports:
          - containerPort: 27017
        resources: {}
        imagePullPolicy: Always
      imagePullSecrets:
        - name: dockercfg-key
      restartPolicy: Always
