apiVersion: v1
kind: Service
metadata:
  labels:
    service: account_mongodb
    app: {{ template "fullname" . }}
    type: db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: account_mongodb
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: account_mongodb
  type: ClusterIP
  ports:
  - name: "26000"
    protocol: TCP
    port: 26000
    targetPort: 27017