apiVersion: v1
kind: Service
metadata:
  labels:
    service: account-service
    app: {{ template "fullname" . }}
    type: service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: account-service
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: account-service
  type: ClusterIP
  ports:
  - name: "6000"
    protocol: TCP
    port: 6000
    targetPort: 6000
