apiVersion: v1
kind: Service
metadata:
  labels:
    service: auth-mongodb
    app: {{ template "fullname" . }}
    type: db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: auth-mongodb
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: auth-mongodb
  type: ClusterIP
  ports:
  - name: "25000"
    port: 25000
    targetPort: 27017
