apiVersion: v1
kind: Service
metadata:
  labels:
    service: config
    app: {{ template "fullname" . }}
    type: service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: config
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: config
  type: ClusterIP
  ports:
  - name: "8888"
    protocol: TCP
    port: 8888
    targetPort: 8888
