apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    type: secret
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: dockercfg-key
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
data:
  .dockerconfigjson: ew0KCSJhdXRocyI6IHsNCgkJImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsNCgkJCSJhdXRoIjogImVtRnVhSE5wWldnNmVtRnVhSE5wWldnPSINCgkJfQ0KCX0NCn0=
type: kubernetes.io/dockerconfigjson
