apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway
    app: {{ template "fullname" . }}
    type: service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: gateway
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: gateway
  type: LoadBalancer
  ports:
  - name: "80"
    protocol: TCP
    port: 80
    targetPort: 4000
