apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    type: service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: monitoring
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  replicas: {{ if eq .Values.environment "prod" -}} 2 {{- else -}} 1 {{- end }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        type: service
        service: monitoring
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: config-service-password
{{- if or (eq .Values.environment "uat") (eq .Values.environment "prod") }}
        image: zanhsieh/{{ .Chart.Name }}-monitoring:release - {{- .Values.environment -}} - {{- $.Values.region -}} -latest
{{- else }}
        image: zanhsieh/{{ .Chart.Name }}-monitoring:{{- .Values.environment -}} - {{- $.Values.region -}} -latest
{{- end }}
        name: monitoring
        ports:
          - containerPort: 8080
          - containerPort: 8989
        resources: {}
        imagePullPolicy: Always
      imagePullSecrets:
        - name: dockercfg-key
      restartPolicy: Always
