apiVersion: v1
kind: Service
metadata:
  labels:
    service: monitoring
    app: {{ template "fullname" . }}
    type: service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: monitoring
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: monitoring
  type: LoadBalancer
  ports:
  - name: "9000"
    protocol: TCP
    port: 9000
    targetPort: 8080
  - name: "8989"
    protocol: TCP
    port: 8989
    targetPort: 8989
