apiVersion: v1
kind: Service
metadata:
  labels:
    service: notification-mongodb
    app: {{ template "fullname" . }}
    type: db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: notification-mongodb
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: notification-mongodb
  type: ClusterIP
  ports:
  - name: "28000"
    protocol: TCP
    port: 28000
    targetPort: 27017