apiVersion: v1
kind: Service
metadata:
  labels:
    service: registry
    app: {{ template "fullname" . }}
    type: service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: registry
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: registry
  type: LoadBalancer
  ports:
  - name: "8761"
    protocol: TCP
    port: 8761
    targetPort: 8761
