apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
type: Opaque
data:
  account-service-password: {{ default "password" .Values.accountServicePassword | b64enc | quote }}
  config-service-password: {{ default "password" .Values.configServicePassword | b64enc | quote }}
  mongodb-password: {{ default "password" .Values.mongodbPassword | b64enc | quote }}
  notification-service-password: {{ default "password" .Values.notificationServicePassword | b64enc | quote }}
  statistics-service-password: {{ default "password" .Values.statisticsServicePassword | b64enc | quote }}