apiVersion: v1
kind: Service
metadata:
  labels:
    service: statistics-mongodb
    app: {{ template "fullname" . }}
    type: db
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: statistics-mongodb
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: statistics-mongodb
  type: ClusterIP
  ports:
  - name: "27000"
    protocol: TCP
    port: 27000
    targetPort: 27017