apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "fullname" . }}
    type: service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: statistics_service
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  replicas: {{ if eq .Values.environment "prod" -}} 2 {{- else -}} 1 {{- end }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        type: service
        service: statistics_service
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: config-service-password
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mongodb-password
        - name: STATISTICS_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: statistics-service-password
{{- if or (eq .Values.environment "uat") (eq .Values.environment "prod") }}
        image: zanhsieh/{{ template "fullname" . }}-account-service:release - {{- .Values.environment -}} - {{- $.Values.region -}} -latest
{{- else }}
        image: zanhsieh/{{ template "fullname" . }}-account-service:{{- .Values.environment -}} - {{- $.Values.region -}} -latest
{{- end }}
        name: statistics_service
        ports:
          - name: "7000"
            containerPort: 7000
        resources: {}
        imagePullPolicy: Always
      imagePullSecrets:
        - name: dockercfg-key
      restartPolicy: Always
