apiVersion: v1
kind: Service
metadata:
  labels:
    service: statistics_service
    app: {{ template "fullname" . }}
    type: service
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: statistics_service
  namespace: {{ template "fullname" . }}- {{- .Values.environment -}} - {{- .Values.region }}
spec:
  selector:
    service: statistics_service
  type: ClusterIP
  ports:
  - name: "7000"
    protocol: TCP
    port: 7000
    targetPort: 7000