apiVersion: v1
kind: Service
metadata:
  labels:
    service: account_mongodb
  name: account_mongodb
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: account_mongodb
