apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account_mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: account_mongodb
    spec:
      containers:
      - env:
        - name: INIT_DUMP
          value: account-service-dump.js
        - name: MONGODB_PASSWORD
        image: zanhsieh/piggymetrics-mongodb
        name: account_mongodb
        resources: {}
      restartPolicy: Always
