apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: config
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: config
    spec:
      containers:
      - env:
        - name: CONFIG_SERVICE_PASSWORD
        image: zanhsieh/piggymetrics-config
        name: config
        resources: {}
      restartPolicy: Always
status: {}
