apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: config
  name: config
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: config
status:
  loadBalancer: {}
