apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway
  name: gateway
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 4000
  selector:
    service: gateway
  type: LoadBalancer
