apiVersion: v1
kind: Service
metadata:
  labels:
    service: monitoring
  name: monitoring
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 8080
  - name: "8989"
    port: 8989
    targetPort: 8989
  selector:
    service: monitoring
  type: LoadBalancer
