apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: notification_mongodb
  name: notification_mongodb
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: notification_mongodb
status:
  loadBalancer: {}
