apiVersion: v1
kind: Service
metadata:
  labels:
    service: registry
  name: registry
spec:
  ports:
  - name: "8761"
    port: 8761
    targetPort: 8761
  selector:
    service: registry
  type: LoadBalancer
