apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statistics_mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: statistics_mongodb
    spec:
      containers:
      - env:
        - name: MONGODB_PASSWORD
        image: zanhsieh/piggymetrics-mongodb
        name: statistics_mongodb
        resources: {}
      restartPolicy: Always
status: {}
