apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: statistics_service
  name: statistics_service
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: statistics_service
status:
  loadBalancer: {}
